"""Catalogue de demonstration, hors execution et hors secrets."""
from __future__ import annotations

from .models import ModelProfile

DEFAULT_MODELS: tuple[ModelProfile, ...] = (
    ModelProfile(
        id="demo-cheap",
        name="Demo Cheap",
        provider="demo",
        model="demo-cheap",
        base_url="https://demo.local/v1",
        api_key_env="",
        quality=0.52,
        cost=0.08,
        latency=0.28,
        capabilities=("chat", "json", "summary"),
        context_window=8192,
        fallback_id="demo-balanced",
        scope="demo",
        optional_key=True,
    ),
    ModelProfile(
        id="demo-quality",
        name="Demo Quality",
        provider="demo",
        model="demo-quality",
        base_url="https://demo.local/v1",
        api_key_env="",
        quality=0.96,
        cost=0.82,
        latency=0.48,
        capabilities=("chat", "tools", "json", "coding", "reasoning"),
        context_window=200000,
        fallback_id="demo-balanced",
        scope="demo",
        optional_key=True,
    ),
    ModelProfile(
        id="demo-fast",
        name="Demo Fast",
        provider="demo",
        model="demo-fast",
        base_url="https://demo.local/v1",
        api_key_env="",
        quality=0.62,
        cost=0.22,
        latency=0.08,
        capabilities=("chat", "json"),
        context_window=8192,
        fallback_id="demo-cheap",
        scope="demo",
        optional_key=True,
    ),
    ModelProfile(
        id="demo-balanced",
        name="Demo Balanced",
        provider="demo",
        model="demo-balanced",
        base_url="https://demo.local/v1",
        api_key_env="",
        quality=0.84,
        cost=0.36,
        latency=0.30,
        capabilities=("chat", "tools", "json"),
        context_window=128000,
        fallback_id="demo-cheap",
        scope="demo",
        optional_key=True,
    ),
    ModelProfile(
        id="demo-vision",
        name="Demo Vision",
        provider="demo",
        model="demo-vision",
        base_url="https://demo.local/v1",
        api_key_env="",
        quality=0.80,
        cost=0.48,
        latency=0.36,
        capabilities=("chat", "vision", "image"),
        context_window=128000,
        fallback_id="demo-balanced",
        scope="demo",
        optional_key=True,
    ),
)
